# Generated by Django 5.0.14 on 2026-06-03 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=220)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('office', 'Office')], db_index=True, max_length=30)),
                ('bedrooms', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('area_sqft', models.PositiveIntegerField(db_index=True)),
                ('furnishing', models.CharField(blank=True, db_index=True, max_length=80)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking', models.PositiveSmallIntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='properties/covers/')),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('locality', models.CharField(db_index=True, max_length=140)),
                ('pincode', models.CharField(db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('rented', 'Rented')], db_index=True, default='active', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'locality'], name='properties__city_23f8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['approval_status', 'status'], name='properties__approva_e83bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price', 'area_sqft'], name='properties__price_37310d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties__latitud_6eb2b0_idx'),
        ),
    ]
