# Generated by Django 5.0.14 on 2026-06-08 09:55

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.upload_property_cover),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.upload_property_gallery),
        ),
    ]
