# Generated by Django 5.0.14 on 2026-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_sold_date_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('sold', 'Sold'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
    ]
