# Generated by Django 5.0.14 on 2026-06-11 10:12

import django.core.validators
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_sqft',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[properties.models.validate_year_built]),
        ),
    ]
