# Generated by Django 5.0.14 on 2026-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('inquiry', 'Inquiry'), ('visit', 'Visit'), ('favorite', 'Favorite'), ('lead', 'Lead'), ('approval', 'Approval'), ('search', 'Search')], db_index=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], db_index=True, default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notification_user__bc8e21_idx'),
        ),
    ]
