# Generated by Django 5.0.14 on 2026-06-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_f2ad08_idx',
            old_name='notification_user__bc8e21_idx',
        ),
    ]
