# Generated by Django 5.0.14 on 2026-06-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='search_sear_user_id_71e095_idx',
            old_name='search_sear_user_id_c4f8a1_idx',
        ),
    ]
