# Generated by Django 5.0.14 on 2026-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('inquiry', 'Inquiry'), ('visit', 'Visit'), ('favorite', 'Favorite'), ('lead', 'Lead'), ('approval', 'Approval'), ('search', 'Search'), ('profile', 'Profile')], db_index=True, default='system', max_length=20),
        ),
    ]
